server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    freemarker:
      check-template-location: true
    cache: true
    servlet:
      content-type: text/html
      multipart:
        max-file-size: 1024Mb
        max-request-size: 2048Mb
    enabled: true
    encoding: utf-8
    excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/travel
    data-username: root
    data-password: "123456"
    #配置监控统计拦截的filters，去掉后面监控界面sql将无法统计，wall用于防火墙
    filters: stat,wall,log4j
    #最大活跃数
    maxAction: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来开启mergesql功能，慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minldle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableldleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileldle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
  #配置redis数据库连接
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
      timeout: 2000
    database: 0


mybatis:
  mapper-locations: classpath:mapper/*.xml
#student:
 # name: lv
  #passWord: 12345

# Enable template caching.
#spring.thymeleaf.cache=true
# Check that the templates location exists.
#spring.thymeleaf.check-template-location=true
# Content-Type value.
#spring.thymeleaf.servlet.content-type=text/html
# Enable MVC Thymeleaf view resolution.
#spring.thymeleaf.enabled=true
# Template encoding.
#spring.thymeleaf.encoding=UTF-8
# Comma-separated list of view names that should be excluded from resolution.
#spring.thymeleaf.excluded-view-names=
# Template mode to be applied to templates. See also StandardTemplateModeHandlers.
#spring.thymeleaf.mode=HTML
# Prefix that gets prepended to view names when building a URL.
#spring.thymeleaf.prefix=classpath:/templates/
# Suffix that gets appended to view names when building a URL.
#spring.thymeleaf.suffix=.html